Repository googleapis/nodejs-appengine-admin, pull requests merged in 2021-05, with the labels that each got.

#36 build: add generated-files bot config
  .github/generated-files-bot.yml
  .kokoro/release/publish.cfg
  synth.metadata
Labels: api: appengine, api: automl, automerge, cla: yes, context: full

#38 build: update to falsy behavior in protos
  protos/protos.d.ts
  protos/protos.js
Labels: api: appengine, automerge, cla: yes, context: none

#22 chore: migrate to owl bot
  .github/.OwlBot.lock.yaml
  .github/.OwlBot.yaml
  .github/workflows/ci.yaml
  .repo-metadata.json
  owlbot.py
  protos/protos.d.ts
  protos/protos.js
  synth.metadata
Labels: api: appengine, cla: yes

#39 fix(deps): require google-gax v2.12.0
  package.json
Labels: api: appengine, automerge, cla: yes
